-- Script SQL pour créer la table des points
CREATE DATABASE IF NOT EXISTS siteproto CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE siteproto;

CREATE TABLE IF NOT EXISTS points (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
